name: ${project.name}
main: com.promcteam.fabled.parties.FabledParties
version: ${project.version}
api-version: 1.13
authors: [ Eniripsa96, Sentropic, ProMCTeam ]
depend: [ Fabled ]
softdepend: [ Instances, PlaceholderAPI ]

permissions:
  fabled.party.general:
    default: true