name: ${project.name}
main: studio.magemonkey.fabled.parties.FabledParties
version: ${project.version}
api-version: 1.16
authors: [ Eniripsa96, Sentropic, MageMonkeyStudio ]
depend: [ Fabled ]
softdepend: [ Instances, PlaceholderAPI ]

permissions:
  fabled.party.general:
    default: true